// Code generated by protoc-gen-go-ttrpc. DO NOT EDIT.
// source: shim.proto
package task

import (
	context "context"
	ttrpc "github.com/containerd/ttrpc"
)

type TaskService interface {
	Create(context.Context, *CreateTaskRequest) (*CreateTaskResponse, error)
}

func RegisterTaskService(srv *ttrpc.Server, svc TaskService) {
	srv.RegisterService("task.Task", &ttrpc.ServiceDesc{
		Methods: map[string]ttrpc.Method{
			"Create": func(ctx context.Context, unmarshal func(interface{}) error) (interface{}, error) {
				var req CreateTaskRequest
				if err := unmarshal(&req); err != nil {
					return nil, err
				}
				return svc.Create(ctx, &req)
			},
		},
	})
}

type taskClient struct {
	client *ttrpc.Client
}

func NewTaskClient(client *ttrpc.Client) TaskService {
	return &taskClient{
		client: client,
	}
}

func (c *taskClient) Create(ctx context.Context, req *CreateTaskRequest) (*CreateTaskResponse, error) {
	var resp CreateTaskResponse
	if err := c.client.Call(ctx, "task.Task", "Create", req, &resp); err != nil {
		return nil, err
	}
	return &resp, nil
}
